fix(pr template): clarify author section
tome-github/.github pull request #2
Opened 2022-10-12 15:22 UTC by mtfurlan

It wasn't clear that the author section shouldn't describe what the PR
does but rather how to test it.

ticket: DV-none
****
^^^^^ Commit body above, PR title is the commit subject

## Author Section

Is this more clear?

## Reviewer Section
* [ ] Are there no breaking changes / are the breaking changes documented?
* [ ] Are unit tests added? (or not applicable)
* [ ] Do the edited sections of code match our coding standards
  * e.g. naming conventions adhered, no copy/paste, readable, function names describe the behavior
* [ ] Is the documentation still correct? (function descriptions, readme, etc)

Note: Do not press green "squash and merge" or whatever it may say button, add label `automerge` to cause the pr to be automagically merged with the commit message from the PR.

2022-10-12 15:23 UTC, mtfurlan commented
In this case I want everyone to review this so we can make sure we're all on the same page and fix the wording till it makes sense to everyone.

2022-10-12 15:31 UTC, kratman commented
It seems to me that the template is more complicated than it needs to be. If extra stuff is only needed for testing, then why have it in the template and require everyone to delete it?

I would propose just to remove the author/testing-notes section entirely. I don't like having to delete it every time I make a PR and some people just forget to update it all together.

2022-10-12 20:37 UTC, rich-tome approved these changes

2022-10-13 15:19 UTC, rich-tome approved these changes

2022-10-13 17:35 UTC, kratman commented on .github/pull_request_template.md
>  ticket: DV-none
Adding two blank lines here lets the author just type without reformatting anything
```suggestion


ticket: DV-none
```

2022-10-13 17:38 UTC, mtfurlan commented on .github/pull_request_template.md
>  ticket: DV-none
I removed it because when I get dropped into the template it already adds a line there between my commit body and the template, is that not what happens for you?

2022-10-13 17:43 UTC, kratman commented on .github/pull_request_template.md
>  ticket: DV-none
The extra lines might do nothing, I would have to experiment more. What I do know is that I have to add two black lines at the top when I create PRs.

2022-10-13 18:24 UTC, mtfurlan commented on .github/pull_request_template.md
>  ticket: DV-none
If you want to play around just put a .github/pull_request_template.md in https://github.com/tome-github/test on develop and then try making a PR.

2022-10-13 18:46 UTC, kratman commented on .github/pull_request_template.md
>  ticket: DV-none
Ok I will try this out tomorrow

2022-10-21 15:30 UTC, mtfurlan commented on .github/pull_request_template.md
>  ticket: DV-none
Any progress?

2022-10-21 15:36 UTC, rich-tome approved these changes

2022-10-24 20:41 UTC, kratman commented on .github/pull_request_template.md
>  ticket: DV-none
A single blank line does nothing in the PR template
![image](https://user-images.githubusercontent.com/10170302/197624784-17d86bb3-7fcd-42a4-bad9-b0eebe9c4ffb.png)


2 blank lines makes a blank line appear in the text.
![image](https://user-images.githubusercontent.com/10170302/197624901-f3cbbd49-81ea-4d57-b266-6ab55edd7753.png)


I can tell which is which, because I deleted the other stuff in the 2 blank lines version. So the single blank line version is the old template (test done inside circbuf) and the 2 blank line version is from merging a change with the PR template in the test repo. PR templates only take effect after the merge, so I had to merge it then create a new PR to get the result.

2022-10-24 20:48 UTC, kratman requested changes

2022-10-24 20:48 UTC, kratman commented on .github/pull_request_template.md
>  ^^^^^ Commit body above, PR title is the commit subject
I think it would be good to wrap this in a comment so we don't have to see it after the PR is made.

2022-10-24 20:48 UTC, kratman commented on .github/pull_request_template.md
> +## Testing notes from the author
I would still vote to remove most of the stuff in this section. Table, Fix header, Feature header, etc. If we are putting in the table just so we can find how to make one, then a simple markdown cheat sheet somewhere would be better. There are several ones available online.

2022-10-24 21:23 UTC, mtfurlan commented on .github/pull_request_template.md
>  ticket: DV-none
So 0 blank lines would make me happy, 1 makes nobody happy, and 2 would make you happy.

2022-10-24 21:23 UTC, mtfurlan commented on .github/pull_request_template.md
>  ^^^^^ Commit body above, PR title is the commit subject
It is intended as a reminder to the reviewer to think about the final commit body.
Can it be worded better to do that?

2022-10-24 21:24 UTC, mtfurlan commented on .github/pull_request_template.md
> +## Testing notes from the author
The point of a template is to have the stuff you will need handy.

2022-10-24 21:26 UTC, kratman commented on .github/pull_request_template.md
>  ticket: DV-none
My argument for 2 blank lines is so we can just start typing immediately. It is a convenience thing

2022-10-24 21:27 UTC, kratman commented on .github/pull_request_template.md
>  ^^^^^ Commit body above, PR title is the commit subject
My complaint is that it appears in the markdown unless deleted. It is a comment for the author so it does not need to be seen in the rendered markdown

2022-10-24 21:29 UTC, kratman commented on .github/pull_request_template.md
> +## Testing notes from the author
It does not appear to be a common need. Few PRs need tables and none need both fix and feature sections. It is easy enough to type that stuff out as needed

2022-10-24 21:43 UTC, mtfurlan commented on .github/pull_request_template.md
>  ^^^^^ Commit body above, PR title is the commit subject
It is a comment for the reviewer.

2022-10-24 21:44 UTC, mtfurlan commented on .github/pull_request_template.md
>  ticket: DV-none
0 is more convenient if you use github's cli tool.

2022-10-27 15:43 UTC, rich-tome requested changes
I like everything the way it is _except_ put a comment in to clearly state that the purpose of the PR *MUST* by in the commit notes section, and the method of testing for the reviewer's convenience *MUST* be in the author section.
I don't care to lookup markdown syntax or spent time with text formatting---I just wanna read what the PR is for, how to test that PR, and get to the actual reviewing.

2022-10-27 15:49 UTC, rich-tome commented on .github/pull_request_template.md
> +Put notes on how to test in this section.
Good. This should nudge the Author to put the right stuff in the right place.

2022-10-27 15:52 UTC, kratman commented
I still think this is overly complicated. Not all PRs need testing notes, and there is a lot in that template. Most PRs just need a sentence or two saying what they are doing. Having all that boiler plate stuff just makes it look messy and is rarely needed.

2022-10-27 16:09 UTC, mtfurlan commented
Okay so going over what we want in a PR:
* Commit body describing what happened
* Separator for commit body for automerge script
* Comment to tell people how wide a commit body can be
* Comment on where to put stuff because people keep putting descriptions about what a PR does in the testing section
* testing notes section with template
* Checkboxes so a reviewer can promise they manually checked each thing

Re-evaluating the template based on that, I removed some unnecessary stuff but I'm not removing the table.
It's in a comment, it doesn't show up except when editing so I don't feel it's in the way.

2022-11-07 21:47 UTC, rich-tome approved these changes

2022-11-07 22:25 UTC, kratman approved these changes
Fine by me

2022-11-08 14:15 UTC, mbush91 approved these changes

2022-11-09 16:49 UTC, kratman commented
Can this be merged now?

2022-11-09 16:54 UTC, merged